<?php
class UserGradeLevelSeeder extends Seeder
{
    /**
     * Run on the command line:
     * php index.php database seed UserGradeLevelSeeder
     */
    public function run()
    {
        $this->ci->load->model('User_grade_level_model');

        $data = array(
            0 => array('id' => '1', 'term_id' => '3', 'grade_level_id' => '27', 'user_id' => '38'),
            1 => array('id' => '2', 'term_id' => '3', 'grade_level_id' => '28', 'user_id' => '38'),
            2 => array('id' => '3', 'term_id' => '3', 'grade_level_id' => '11', 'user_id' => '27'),
            3 => array('id' => '4', 'term_id' => '3', 'grade_level_id' => '12', 'user_id' => '27'),
            4 => array('id' => '5', 'term_id' => '3', 'grade_level_id' => '17', 'user_id' => '2'),
            5 => array('id' => '6', 'term_id' => '3', 'grade_level_id' => '25', 'user_id' => '2'),
            6 => array('id' => '7', 'term_id' => '3', 'grade_level_id' => '26', 'user_id' => '2'),
            7 => array('id' => '8', 'term_id' => '3', 'grade_level_id' => '27', 'user_id' => '2'),
            8 => array('id' => '9', 'term_id' => '3', 'grade_level_id' => '28', 'user_id' => '2'),
            9 => array('id' => '10', 'term_id' => '3', 'grade_level_id' => '13', 'user_id' => '23'),
            10 => array('id' => '11', 'term_id' => '3', 'grade_level_id' => '11', 'user_id' => '39'),
            11 => array('id' => '12', 'term_id' => '3', 'grade_level_id' => '12', 'user_id' => '39'),
            12 => array('id' => '13', 'term_id' => '3', 'grade_level_id' => '13', 'user_id' => '39'),
            13 => array('id' => '14', 'term_id' => '3', 'grade_level_id' => '15', 'user_id' => '39'),
            14 => array('id' => '15', 'term_id' => '3', 'grade_level_id' => '16', 'user_id' => '39'),
            15 => array('id' => '16', 'term_id' => '3', 'grade_level_id' => '17', 'user_id' => '42'),
            16 => array('id' => '17', 'term_id' => '3', 'grade_level_id' => '18', 'user_id' => '42'),
            17 => array('id' => '18', 'term_id' => '3', 'grade_level_id' => '19', 'user_id' => '42'),
            18 => array('id' => '19', 'term_id' => '3', 'grade_level_id' => '21', 'user_id' => '42'),
            19 => array('id' => '20', 'term_id' => '3', 'grade_level_id' => '22', 'user_id' => '42'),
            20 => array('id' => '21', 'term_id' => '3', 'grade_level_id' => '25', 'user_id' => '36'),
            21 => array('id' => '22', 'term_id' => '3', 'grade_level_id' => '26', 'user_id' => '36'),
            22 => array('id' => '23', 'term_id' => '3', 'grade_level_id' => '2', 'user_id' => '22'),
            23 => array('id' => '24', 'term_id' => '3', 'grade_level_id' => '18', 'user_id' => '9'),
            24 => array('id' => '25', 'term_id' => '3', 'grade_level_id' => '19', 'user_id' => '9'),
            25 => array('id' => '26', 'term_id' => '3', 'grade_level_id' => '21', 'user_id' => '9'),
            26 => array('id' => '27', 'term_id' => '3', 'grade_level_id' => '22', 'user_id' => '9'),
            27 => array('id' => '28', 'term_id' => '3', 'grade_level_id' => '23', 'user_id' => '9'),
            28 => array('id' => '29', 'term_id' => '3', 'grade_level_id' => '24', 'user_id' => '9'),
            29 => array('id' => '30', 'term_id' => '3', 'grade_level_id' => '25', 'user_id' => '9'),
            30 => array('id' => '31', 'term_id' => '3', 'grade_level_id' => '26', 'user_id' => '9'),
            31 => array('id' => '32', 'term_id' => '3', 'grade_level_id' => '27', 'user_id' => '9'),
            32 => array('id' => '33', 'term_id' => '3', 'grade_level_id' => '28', 'user_id' => '9'),
            33 => array('id' => '34', 'term_id' => '3', 'grade_level_id' => '9', 'user_id' => '32'),
            34 => array('id' => '35', 'term_id' => '3', 'grade_level_id' => '6', 'user_id' => '26'),
            35 => array('id' => '36', 'term_id' => '3', 'grade_level_id' => '5', 'user_id' => '15'),
            36 => array('id' => '37', 'term_id' => '3', 'grade_level_id' => '8', 'user_id' => '30'),
            37 => array('id' => '38', 'term_id' => '3', 'grade_level_id' => '17', 'user_id' => '35'),
            38 => array('id' => '39', 'term_id' => '3', 'grade_level_id' => '18', 'user_id' => '35'),
            39 => array('id' => '40', 'term_id' => '3', 'grade_level_id' => '19', 'user_id' => '35'),
            40 => array('id' => '41', 'term_id' => '3', 'grade_level_id' => '21', 'user_id' => '35'),
            41 => array('id' => '42', 'term_id' => '3', 'grade_level_id' => '22', 'user_id' => '35'),
            42 => array('id' => '43', 'term_id' => '3', 'grade_level_id' => '3', 'user_id' => '37'),
            43 => array('id' => '44', 'term_id' => '3', 'grade_level_id' => '4', 'user_id' => '12'),
            44 => array('id' => '45', 'term_id' => '3', 'grade_level_id' => '25', 'user_id' => '7'),
            45 => array('id' => '46', 'term_id' => '3', 'grade_level_id' => '26', 'user_id' => '7'),
            46 => array('id' => '47', 'term_id' => '3', 'grade_level_id' => '15', 'user_id' => '6'),
            47 => array('id' => '48', 'term_id' => '3', 'grade_level_id' => '16', 'user_id' => '6'),
            48 => array('id' => '49', 'term_id' => '3', 'grade_level_id' => '11', 'user_id' => '20'),
            49 => array('id' => '50', 'term_id' => '3', 'grade_level_id' => '12', 'user_id' => '20'),
            50 => array('id' => '51', 'term_id' => '3', 'grade_level_id' => '23', 'user_id' => '1'),
            51 => array('id' => '52', 'term_id' => '3', 'grade_level_id' => '24', 'user_id' => '1'),
            52 => array('id' => '53', 'term_id' => '3', 'grade_level_id' => '5', 'user_id' => '28'),
            53 => array('id' => '54', 'term_id' => '3', 'grade_level_id' => '6', 'user_id' => '28'),
            54 => array('id' => '55', 'term_id' => '3', 'grade_level_id' => '7', 'user_id' => '28'),
            55 => array('id' => '56', 'term_id' => '3', 'grade_level_id' => '8', 'user_id' => '28'),
            56 => array('id' => '57', 'term_id' => '3', 'grade_level_id' => '9', 'user_id' => '28'),
            57 => array('id' => '58', 'term_id' => '3', 'grade_level_id' => '10', 'user_id' => '28'),
            58 => array('id' => '59', 'term_id' => '3', 'grade_level_id' => '11', 'user_id' => '28'),
            59 => array('id' => '60', 'term_id' => '3', 'grade_level_id' => '12', 'user_id' => '28'),
            60 => array('id' => '61', 'term_id' => '3', 'grade_level_id' => '13', 'user_id' => '28'),
            61 => array('id' => '62', 'term_id' => '3', 'grade_level_id' => '15', 'user_id' => '28'),
            62 => array('id' => '63', 'term_id' => '3', 'grade_level_id' => '16', 'user_id' => '28'),
            63 => array('id' => '64', 'term_id' => '3', 'grade_level_id' => '2', 'user_id' => '5'),
            64 => array('id' => '65', 'term_id' => '3', 'grade_level_id' => '1', 'user_id' => '5'),
            65 => array('id' => '66', 'term_id' => '3', 'grade_level_id' => '3', 'user_id' => '5'),
            66 => array('id' => '67', 'term_id' => '3', 'grade_level_id' => '7', 'user_id' => '34'),
            67 => array('id' => '68', 'term_id' => '3', 'grade_level_id' => '17', 'user_id' => '18'),
            68 => array('id' => '69', 'term_id' => '3', 'grade_level_id' => '18', 'user_id' => '18'),
            69 => array('id' => '70', 'term_id' => '3', 'grade_level_id' => '19', 'user_id' => '18'),
            70 => array('id' => '71', 'term_id' => '3', 'grade_level_id' => '28', 'user_id' => '40'),
            71 => array('id' => '72', 'term_id' => '3', 'grade_level_id' => '21', 'user_id' => '11'),
            72 => array('id' => '73', 'term_id' => '3', 'grade_level_id' => '22', 'user_id' => '11'),
            73 => array('id' => '74', 'term_id' => '3', 'grade_level_id' => '23', 'user_id' => '11'),
            74 => array('id' => '75', 'term_id' => '3', 'grade_level_id' => '24', 'user_id' => '11'),
            75 => array('id' => '76', 'term_id' => '3', 'grade_level_id' => '21', 'user_id' => '13'),
            76 => array('id' => '77', 'term_id' => '3', 'grade_level_id' => '22', 'user_id' => '13'),
            77 => array('id' => '78', 'term_id' => '3', 'grade_level_id' => '23', 'user_id' => '13'),
            78 => array('id' => '79', 'term_id' => '3', 'grade_level_id' => '24', 'user_id' => '13'),
            79 => array('id' => '80', 'term_id' => '3', 'grade_level_id' => '10', 'user_id' => '29'),
            80 => array('id' => '81', 'term_id' => '3', 'grade_level_id' => '7', 'user_id' => '21'),
            81 => array('id' => '82', 'term_id' => '3', 'grade_level_id' => '8', 'user_id' => '21'),
            82 => array('id' => '83', 'term_id' => '3', 'grade_level_id' => '9', 'user_id' => '21'),
            83 => array('id' => '84', 'term_id' => '3', 'grade_level_id' => '10', 'user_id' => '21'),
            84 => array('id' => '85', 'term_id' => '3', 'grade_level_id' => '11', 'user_id' => '21'),
            85 => array('id' => '86', 'term_id' => '3', 'grade_level_id' => '12', 'user_id' => '21'),
            86 => array('id' => '87', 'term_id' => '3', 'grade_level_id' => '13', 'user_id' => '21'),
            87 => array('id' => '88', 'term_id' => '3', 'grade_level_id' => '15', 'user_id' => '21'),
            88 => array('id' => '89', 'term_id' => '3', 'grade_level_id' => '16', 'user_id' => '21'),
            89 => array('id' => '90', 'term_id' => '3', 'grade_level_id' => '1', 'user_id' => '10'),
            90 => array('id' => '91', 'term_id' => '3', 'grade_level_id' => '25', 'user_id' => '8'),
            91 => array('id' => '92', 'term_id' => '3', 'grade_level_id' => '26', 'user_id' => '8'),
            92 => array('id' => '93', 'term_id' => '3', 'grade_level_id' => '27', 'user_id' => '8'),
            93 => array('id' => '94', 'term_id' => '3', 'grade_level_id' => '28', 'user_id' => '8'),
            94 => array('id' => '95', 'term_id' => '3', 'grade_level_id' => '17', 'user_id' => '17'),
            95 => array('id' => '96', 'term_id' => '3', 'grade_level_id' => '18', 'user_id' => '17'),
            96 => array('id' => '97', 'term_id' => '3', 'grade_level_id' => '19', 'user_id' => '17'),
            97 => array('id' => '98', 'term_id' => '3', 'grade_level_id' => '21', 'user_id' => '17'),
            98 => array('id' => '99', 'term_id' => '3', 'grade_level_id' => '22', 'user_id' => '17'),
            99 => array('id' => '100', 'term_id' => '3', 'grade_level_id' => '23', 'user_id' => '17'),
            100 => array('id' => '101', 'term_id' => '3', 'grade_level_id' => '24', 'user_id' => '17'),
            101 => array('id' => '102', 'term_id' => '3', 'grade_level_id' => '25', 'user_id' => '17'),
            102 => array('id' => '103', 'term_id' => '3', 'grade_level_id' => '26', 'user_id' => '17'),
            103 => array('id' => '104', 'term_id' => '3', 'grade_level_id' => '25', 'user_id' => '33'),
            104 => array('id' => '105', 'term_id' => '3', 'grade_level_id' => '26', 'user_id' => '33'),
            105 => array('id' => '106', 'term_id' => '3', 'grade_level_id' => '27', 'user_id' => '33'),
            106 => array('id' => '107', 'term_id' => '3', 'grade_level_id' => '28', 'user_id' => '33'),
            107 => array('id' => '108', 'term_id' => '3', 'grade_level_id' => '5', 'user_id' => '14'),
            108 => array('id' => '109', 'term_id' => '3', 'grade_level_id' => '6', 'user_id' => '14'),
            109 => array('id' => '110', 'term_id' => '3', 'grade_level_id' => '9', 'user_id' => '14'),
            110 => array('id' => '111', 'term_id' => '3', 'grade_level_id' => '10', 'user_id' => '14'),
            111 => array('id' => '112', 'term_id' => '3', 'grade_level_id' => '11', 'user_id' => '14'),
            112 => array('id' => '113', 'term_id' => '3', 'grade_level_id' => '12', 'user_id' => '14'),
            113 => array('id' => '114', 'term_id' => '3', 'grade_level_id' => '13', 'user_id' => '14'),
            114 => array('id' => '115', 'term_id' => '3', 'grade_level_id' => '15', 'user_id' => '14'),
            115 => array('id' => '116', 'term_id' => '3', 'grade_level_id' => '16', 'user_id' => '14'),
            116 => array('id' => '117', 'term_id' => '3', 'grade_level_id' => '17', 'user_id' => '24'),
            117 => array('id' => '118', 'term_id' => '3', 'grade_level_id' => '18', 'user_id' => '24'),
            118 => array('id' => '119', 'term_id' => '3', 'grade_level_id' => '19', 'user_id' => '24'),
            119 => array('id' => '120', 'term_id' => '3', 'grade_level_id' => '11', 'user_id' => '24'),
            120 => array('id' => '121', 'term_id' => '3', 'grade_level_id' => '7', 'user_id' => '25'),
            121 => array('id' => '122', 'term_id' => '3', 'grade_level_id' => '8', 'user_id' => '25'),
            122 => array('id' => '123', 'term_id' => '3', 'grade_level_id' => '9', 'user_id' => '25'),
            123 => array('id' => '124', 'term_id' => '3', 'grade_level_id' => '10', 'user_id' => '25'),
            124 => array('id' => '125', 'term_id' => '3', 'grade_level_id' => '4', 'user_id' => '25'),
            125 => array('id' => '126', 'term_id' => '3', 'grade_level_id' => '17', 'user_id' => '16'),
            126 => array('id' => '127', 'term_id' => '3', 'grade_level_id' => '18', 'user_id' => '16'),
            127 => array('id' => '128', 'term_id' => '3', 'grade_level_id' => '19', 'user_id' => '16'),
            128 => array('id' => '129', 'term_id' => '3', 'grade_level_id' => '21', 'user_id' => '19'),
            129 => array('id' => '130', 'term_id' => '3', 'grade_level_id' => '22', 'user_id' => '19'),
            130 => array('id' => '131', 'term_id' => '3', 'grade_level_id' => '23', 'user_id' => '19'),
            131 => array('id' => '132', 'term_id' => '3', 'grade_level_id' => '24', 'user_id' => '19'),
            132 => array('id' => '133', 'term_id' => '3', 'grade_level_id' => '25', 'user_id' => '3'),
            133 => array('id' => '134', 'term_id' => '3', 'grade_level_id' => '26', 'user_id' => '3'),
            134 => array('id' => '135', 'term_id' => '3', 'grade_level_id' => '27', 'user_id' => '3'),
            135 => array('id' => '136', 'term_id' => '3', 'grade_level_id' => '28', 'user_id' => '3'),
            136 => array('id' => '137', 'term_id' => '3', 'grade_level_id' => '23', 'user_id' => '31'),
            137 => array('id' => '138', 'term_id' => '3', 'grade_level_id' => '24', 'user_id' => '31'),
            138 => array('id' => '139', 'term_id' => '3', 'grade_level_id' => '5', 'user_id' => '41'),
            139 => array('id' => '140', 'term_id' => '3', 'grade_level_id' => '6', 'user_id' => '41'),
            140 => array('id' => '141', 'term_id' => '3', 'grade_level_id' => '7', 'user_id' => '41'),
            141 => array('id' => '142', 'term_id' => '3', 'grade_level_id' => '8', 'user_id' => '41'),
            142 => array('id' => '143', 'term_id' => '3', 'grade_level_id' => '11', 'user_id' => '41'),
            143 => array('id' => '144', 'term_id' => '3', 'grade_level_id' => '12', 'user_id' => '41'),
            144 => array('id' => '145', 'term_id' => '3', 'grade_level_id' => '13', 'user_id' => '41'),
            145 => array('id' => '146', 'term_id' => '3', 'grade_level_id' => '15', 'user_id' => '41'),
            146 => array('id' => '147', 'term_id' => '3', 'grade_level_id' => '16', 'user_id' => '41'),
            147 => array('id' => '148', 'term_id' => '3', 'grade_level_id' => '17', 'user_id' => '4'),
            148 => array('id' => '149', 'term_id' => '3', 'grade_level_id' => '18', 'user_id' => '4'),
            149 => array('id' => '150', 'term_id' => '3', 'grade_level_id' => '19', 'user_id' => '4'),
            150 => array('id' => '151', 'term_id' => '3', 'grade_level_id' => '21', 'user_id' => '4'),
            151 => array('id' => '152', 'term_id' => '3', 'grade_level_id' => '22', 'user_id' => '4'),
        );

        $result = $this->ci->User_grade_level_model->insert_many($data, $truncate = TRUE);

        if ($result) {
            echo "$result registros insertados exitosamente" . PHP_EOL;
        }
    }
}
